#!/bin/bash

# Inject the current time into the build process so the container can have some self-awareness
docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" --build-arg BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ') .
